# Jekyll Configuration
safe: true
markdown: rdiscount
pigments: true
permalink: pretty
exclude:
    - bower_components
    - node_modules
    - Gruntfile.js
    - bower.json
    - package.json
    - README.md

# Site
name: Network Chart
baseurl: http://masegalab.github.io/panama-network
github: http://github.com/masegalab/panama-network.git
